browser= chrome
url=https://www.amazon.in/

chrome=webdriver.chrome.driver
chromedriver=C://Users//souravsamanta//Downloads//chromedriver_win32//chromedriver.exe

firefox=webdriver.gecko.driver
firefoxdriver=C://Users//souravsamanta//Downloads//geckodriver-v0.31.0-win64//geckodriver.exe

username=sourav1234@gmail.com
password=123456

implicitWait=10
searchElement=Asus Laptop